ClassJournal.Web/Models/ColumnSortData.cs
using ClassJournal.Models;

namespace ClassJournal.Web.Models
{
	public class ColumnSortData
	{
		public readonly string Name;
		public readonly StudentsSort FieldName;
		public readonly StudentsSort CurrentSort;

		public ColumnSortData(StudentsSort fieldName, StudentsSort currentSort)
		{
			FieldName = fieldName;
			CurrentSort = currentSort;
			
			var member = typeof(StudentsSort).GetField(FieldName.ToString());
			var attribute = (SortAttribute)member.GetCustomAttributes(typeof(SortAttribute), false)[0];
			Name = attribute.Name;
		}
	}
}

ClassJournal.Web/Models/ErrorViewModel.cs
using System;

namespace ClassJournal.Web.Models
{
	public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClassJournal.Web/Models/StudentMarks.cs
using System;
using System.Collections.Generic;
using ClassJournal.Models;

namespace ClassJournal.Web.Models
{
	public class StudentMarks
	{
		public DateTime FirstDate;
		public DateTime LastDate;
		public Student Student;
		public int[] Marks;

		public StudentMarks(Student student, DateTime firstDate, DateTime lastDate)
		{
			Student = student;
			FirstDate = firstDate;
			LastDate = lastDate;
			Marks = new int[(LastDate - FirstDate).Days+1];
		}

		public bool TryAdd(StudentMark mark)
		{
			if (mark == null) throw new ArgumentNullException(nameof(mark));
			if (mark.Date == null)
				return false;
			if (mark.Date.Value.Date > LastDate)
				return false;
			if (mark.Date.Value.Date < FirstDate)
				return false;
			if (mark.StudentId != Student.Id)
				return false;

			Marks[(mark.Date.Value - FirstDate).Days] = mark.Mark;
			return true;
		}
	}
}

ClassJournal.Web/Models/StudentsMarks.cs
using System;
using System.Collections.Generic;
using ClassJournal.Models;

namespace ClassJournal.Web.Models
{
	public class StudentsMarks
	{
		public DateTime FirstDate;
		public DateTime LastDate;
		public DateTime PreviousPeriodFirstDate;
		public DateTime PreviousPeriodLastDate;
		public DateTime NextPeriodFirstDate;
		public DateTime NextPeriodLastDate;
		public List<StudentMarks> Students;
		public bool NextPeriodExists;

		public StudentsMarks(DateTime lastDate, List<Student> students)
		{
			LastDate = lastDate;
			FirstDate = LastDate.AddDays(-32);
			PreviousPeriodFirstDate = FirstDate.AddDays(-33);
			PreviousPeriodLastDate = FirstDate.AddDays(-1);
			NextPeriodFirstDate = LastDate.AddDays(1);
			NextPeriodLastDate = LastDate.AddDays(33);
			if (NextPeriodLastDate > DateTime.Today)
			{
				NextPeriodLastDate = DateTime.Today;
				NextPeriodFirstDate = NextPeriodLastDate.AddDays(-32);
			}

			NextPeriodExists = NextPeriodLastDate > LastDate;

			Students = new List<StudentMarks>();

			foreach (var student in students)
				Students.Add(new StudentMarks(student, FirstDate, LastDate));
			foreach (var mark in StudentMark.SelectAll())
			foreach (var student in Students)
				if (student.TryAdd(mark))
					break;
		}
	}
}

ClassJournal.Web/Controllers/MarksController.cs
using System;
using System.Globalization;
using ClassJournal.Models;
using ClassJournal.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ClassJournal.Web.Controllers
{
	public class MarksController : Controller
	{
		public IActionResult Index(string lastDate)
		{
			DateTime date;
			if (string.IsNullOrEmpty(lastDate))
				date = DateTime.Today;
			else if (!DateTime.TryParseExact(lastDate, "dd.MM.yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
				return BadRequest();
			else if (date > DateTime.Today)
				date = DateTime.Today;

			var model = new StudentsMarks(date, Student.SelectAll(StudentsSort.FirstName));
			return View(model);
		}

		[HttpPost]
		public IActionResult Add(int id, int mark)
		{
			foreach (var studentMark in StudentMark.SelectByStudentId(id))
			{
				if (mark == 0)
				{
					studentMark.Delete();
				}

				else if (studentMark.Date == DateTime.Today)
				{
					studentMark.Mark = mark;
					studentMark.Update();
				}
				break;
			}

			new StudentMark
			{
				Mark = mark,
				StudentId = id,
				Date = DateTime.Now
			}.Insert();
			return RedirectToAction("Index");
		}
	}
}

ClassJournal.Web/Controllers/StudentsController.cs
using System;
using System.Globalization;
using ClassJournal.Models;
using ClassJournal.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ClassJournal.Web.Controllers
{
	public class StudentsController : Controller
    {
        public IActionResult Index(StudentsSort sort)
        {
	        var model = Student.SelectAll(sort);
	        ViewBag.Sort = sort;
            return View(model);
        }

	    public IActionResult Edit(int id = 0)
	    {
		    var model = id > 0 ? Student.GetById(id) : new Student();
		    ViewBag.IsAjax = Request.Method == "POST";
		    return View(model);
	    }

	    [HttpPost]
	    public IActionResult Update(int id, string firstName, string lastName, string birthDate)
	    {
		    var model = id > 0 ? Student.GetById(id) : new Student();
		    model.FirstName = firstName;
		    model.LastName = lastName;
		    if (DateTime.TryParseExact(birthDate, "yyyy-MM-dd", CultureInfo.CurrentCulture, DateTimeStyles.None, out var result))
			    model.Birthdate = result;
		    else
			    model.Birthdate = null;

		    if (id > 0)
			    model.Update();
		    else
			    model.Insert();

		    return RedirectToAction("Index");
	    }

	    [HttpPost]
		public IActionResult Delete(int id)
	    {
		    var model = Student.GetById(id);
			model.Delete();
		    foreach (var studentMark in StudentMark.SelectByStudentId(id))
		    {
				studentMark.Delete();
			}

		    return RedirectToAction("Index");
		}
	}
}

ClassJournal.Web/Views/Marks/AddMark.cshtml
@model List<StudentMark>

@{
	ViewBag.Title = "AddMark";
}
<table class="table table-hover table-condensed table-bordered">
	<th colspan="@Model.Count">Current Marks</th>
	<tr>
		@foreach (var mark in Model)
		{
			<td>
				@mark.Date?.ToString("dd MMMM yyyy")
			</td>
		}
	</tr>
	<tr>
		@foreach (var mark in Model)
		{
		@*<td>
			@($"{Model.FirstName} {Model.LastName}")
		</td>*@
			<td>
				@mark.Mark
			</td>
		}
	</tr>
</table>
<form class="form-horizontal" asp-controller="Marks" asp-action="Update" method="post">
	<input type="hidden" name="Id" value="@Model.">

	<div class="form-group">
		<label for="newMark" class="col-sm-2 control-label">New Mark</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="newMark" name="newMark" value=" ">
		</div>
	</div>
	<div class="form-group">
		<label for="markDate" class="col-sm-2 control-label">Date</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="markDate" name="markDate" value="">
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Save</button>
		</div>
	</div>
</form>

ClassJournal.Web/Views/Marks/Index.cshtml
@model StudentsMarks

@{
	ViewBag.Title = "Marks";
}

<div style="margin-top: 1em; height: 3em">
	<a class="btn btn-primary pull-left" href="@Url.Action("Index", "Marks", new {lastDate=Model.PreviousPeriodLastDate.ToString("dd.MM.yyyy")})">
		@($"{Model.PreviousPeriodFirstDate:dd.MM.yy} - {Model.PreviousPeriodLastDate:dd.MM.yy}")
	</a>
	@if (Model.NextPeriodExists)
	{
		<a class="btn btn-primary pull-right" href="@Url.Action("Index", "Marks", new {lastDate = Model.NextPeriodLastDate.ToString("dd.MM.yyyy")})">
			@($"{Model.NextPeriodFirstDate:dd.MM.yy} - {Model.NextPeriodLastDate:dd.MM.yy}")
		</a>
	}
</div>

<table class="table table-hover table-condensed table-bordered">
	<tr>
		<td></td>
		@{
			for (DateTime i = Model.FirstDate; i <= Model.LastDate;)
			{
				var next = new DateTime(i.Year, i.Month, 1).AddMonths(1);
				if (next > Model.LastDate.AddDays(1))
				{
					next = Model.LastDate.AddDays(1);
				}
				<td colspan="@((next - i).Days)">@i.ToString("MMMM yyyy")</td>
				i = next;
			}
		}
	</tr>

	<tr>
		<td></td>
		@for (DateTime i = Model.FirstDate; i <= Model.LastDate; i = i.AddDays(1))
		{
			<td>@i.Day</td>
		}
	</tr>

	@foreach (var student in Model.Students)
	{
		<tr>
			<td>@($"{student.Student.FirstName} {student.Student.LastName}")</td>
			@{
				foreach (var mark in student.Marks)
				{
					if (mark == 0)
					{
						<td></td>
					}
					else
					{
						<td>@mark</td>
					}
				}
			}
			@if (!Model.NextPeriodExists)
			{
				<td>
					<button class="btn btn-primary add-mark-btn" data-id ="@student.Student.Id">
						Add Mark
					</button>
				</td>
			}
		</tr>
	}
</table>

<div class="modal fade" id="add-mark-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Modal title</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal" asp-controller="Marks" asp-action="Add" method="post">
					<input type="hidden" id="addMarkId" name="id">
					<div class="form-group">
						<label for="addMarkValue" class="col-sm-2 control-label">Введите оценку</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="addMarkValue" name="mark">
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-default">Save</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script type="text/javascript">
		$(function () {
			$(".add-mark-btn").click(function () {
				var $target = $(this);
				var id = $target.data("id");
				$('#add-mark-modal').modal();
				$('#addMarkId').val(id);
				$('#addMarkValue').val("");
			});
		});
	</script>
}

ClassJournal.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassJournal.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ClassJournal.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Students" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Marks" asp-action="Index">Marks</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ClassJournal.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ClassJournal.Web/Views/Students/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ClassJournal.Web/Views/Students/ColumnSortLink.cshtml
@model ColumnSortData

@if (Model.CurrentSort == Model.FieldName)
{
	<a href="@Url.Action("Index", "Students")?sort=@(Model.FieldName+1)">@Model.Name <i class="glyphicon glyphicon-sort-by-attributes"></i></a>
}
else if (Model.CurrentSort == Model.FieldName+1)
{
	<a href="@Url.Action("Index", "Students")">@Model.Name <i class="glyphicon glyphicon-sort-by-attributes-alt"></i></a>
}
else
{
	<a href="@Url.Action("Index", "Students")?sort=@Model.FieldName">@Model.Name</a>
}

ClassJournal.Web/Views/Students/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ClassJournal.Web/Views/Students/Edit.cshtml
@model Student

@{
	ViewBag.Title = "title";
	if (ViewBag.IsAjax == true)
	{
		Layout = null;
	}
}
<br/>
<form class="form-horizontal" asp-controller="Students" asp-action="Update" method="post">
	<input type="hidden" name="Id" value="@Model.Id">
	<div class="form-group">
		<label for="FirstName" class="col-sm-2 control-label">FirstName</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="FirstName" name="FirstName" value="@Model.FirstName">
		</div>
	</div>
	<div class="form-group">
		<label for="LastName" class="col-sm-2 control-label">LastName</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="LastName" name="LastName" value="@Model.LastName">
		</div>
	</div>
	<div class="form-group">
		<label for="BirthDate" class="col-sm-2 control-label">BirthDate</label>
		<div class="col-sm-10">
			<input type="date" class="form-control" id="BirthDate" name="BirthDate" value="@Model.Birthdate?.ToString("yyyy-MM-dd")">
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Save</button>
		</div>
	</div>
</form>

ClassJournal.Web/Views/Students/Index.cshtml
@model List<Student>
@{
	ViewData["Title"] = "Home Page";
	var sort = (StudentsSort)ViewBag.Sort;
}
<table class="table table-hover table-condensed table-bordered">
	<tr>
		<th><partial name="ColumnSortLink" model="@(new ColumnSortData(StudentsSort.FirstName, sort))" /></th>
		<th><partial name="ColumnSortLink" model="@(new ColumnSortData(StudentsSort.LastName, sort))" /></th>
		<th><partial name="ColumnSortLink" model="@(new ColumnSortData(StudentsSort.Birthdate, sort))" /></th>
		<th><partial name="ColumnSortLink" model="@(new ColumnSortData(StudentsSort.AverageMark, sort))" /></th>
		<th><partial name="ColumnSortLink" model="@(new ColumnSortData(StudentsSort.LastMark, sort))" /></th>
		<td>
			<a class="btn btn-primary edit-student-link" href="@Url.Action("Edit", "Students")">
				New student...
			</a>
		</td>
	</tr>

	@foreach (var student in Model)
	{
		<tr>
			<td>@student.FirstName</td>
			<td>@student.LastName</td>
			<td>@student.Birthdate</td>
			<td>@student.AverageMark</td>
			<td>@student.LastMark</td>
			<td>
				<a class="btn btn-primary edit-student-link" href="@Url.Action("Edit", "Students", new {id = student.Id})">
					<i class="glyphicon glyphicon-edit"></i>
				</a>
				<form asp-controller="Students" asp-action="Delete" method="post" style="display:inline">
					<input type="hidden" name="Id" value="@student.Id">
					<button class="btn btn-danger" type="submit">
						<i class="glyphicon glyphicon-remove-sign"></i>
					</button>
				</form>
			</td>

		</tr>
	}
</table>

<div class="modal fade" id="edit-student-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Modal title</h4>
			</div>
			<div class="modal-body">
				
			</div>
			@*<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Save changes</button>
			</div>*@
		</div>
	</div>
</div>

@section Scripts {
	<script type="text/javascript">
		$(function () {
			$(".edit-student-link").click(function (ev) {
				ev.preventDefault();

				var $target = $(this);
				var href = $target.attr("href");

				$.post(href, {},
					function(data) {
						$('#edit-student-modal .modal-body').html(data);
						$('#edit-student-modal').modal();
					});
			});
		});
	</script>
}